name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Publish Blazor WebAssembly
        run: dotnet publish SlowLivingCompass.Client/SlowLivingCompass.Client.csproj -c Release -o release -p:BlazorStaticAssetFingerprinting=false

      - name: Change base-tag in index.html from / to SlowLivingCompass
        run: sed -i 's/<base href="\/" \/>/<base href="\/SlowLivingCompass\/" \/>/g' release/wwwroot/index.html

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: release/wwwroot
